import { EconomicIndicator } from '@/lib/types';
const generateSparklineData = (base: number, points: number, trend: number): { date: string; value: number }[] => {
  return Array.from({ length: points }, (_, i) => ({
    date: `T-${points - i}`,
    value: parseFloat((base + (Math.random() - 0.5) * (base / 10) + i * trend).toFixed(2)),
  }));
};
export const mockIndicators: EconomicIndicator[] = [
  {
    id: 'ocr',
    title: 'Official Cash Rate (OCR)',
    value: '5.50%',
    change: '+0.00%',
    changeType: 'neutral',
    description: 'The Official Cash Rate (OCR) is the interest rate set by the Reserve Bank of New Zealand to meet its inflation targets.',
    source: 'Reserve Bank of New Zealand (RBNZ)',
    historicalData: generateSparklineData(5.5, 12, 0),
  },
  {
    id: 'gdp',
    title: 'GDP (Quarterly)',
    value: '-0.1%',
    change: '-0.2%',
    changeType: 'negative',
    description: 'Gross Domestic Product (GDP) measures the total value of goods and services produced in New Zealand.',
    source: 'Stats NZ',
    historicalData: generateSparklineData(0.5, 12, -0.05),
  },
  {
    id: 'cpi',
    title: 'Consumer Price Index (CPI)',
    value: '4.0%',
    change: '-0.7%',
    changeType: 'positive',
    description: 'The Consumer Price Index (CPI) measures the average change in prices paid by households for goods and services.',
    source: 'Stats NZ',
    historicalData: generateSparklineData(4.7, 12, -0.06),
  },
  {
    id: 'unemployment',
    title: 'Unemployment Rate',
    value: '4.3%',
    change: '+0.3%',
    changeType: 'negative',
    description: 'The percentage of the labor force that is jobless and actively looking for employment.',
    source: 'Stats NZ',
    historicalData: generateSparklineData(4.0, 12, 0.03),
  },
  {
    id: 'current_account',
    title: 'Current Account Balance',
    value: '-$7.8B',
    change: '+$1.2B',
    changeType: 'positive',
    description: 'The current account records a nation\'s transactions with the rest of the world—specifically its net trade in goods and services.',
    source: 'Stats NZ',
    historicalData: generateSparklineData(-9.0, 12, 0.1),
  },
  {
    id: 'labour_participation',
    title: 'Labour Force Participation',
    value: '71.9%',
    change: '-0.1%',
    changeType: 'negative',
    description: 'The proportion of the working-age population that is either employed or actively looking for work.',
    source: 'Stats NZ',
    historicalData: generateSparklineData(72.0, 12, -0.01),
  },
  {
    id: 'govt_debt_gdp',
    title: 'Govt. Debt-to-GDP',
    value: '43.5%',
    change: '+1.5%',
    changeType: 'negative',
    description: 'The ratio of government debt to the country\'s Gross Domestic Product (GDP).',
    source: 'The Treasury',
    historicalData: generateSparklineData(42.0, 12, 0.13),
  },
  {
    id: 'exchange_rate_usd',
    title: 'Exchange Rate (NZD/USD)',
    value: '0.61',
    change: '+0.005',
    changeType: 'positive',
    description: 'The value of the New Zealand Dollar compared to the United States Dollar.',
    source: 'Reserve Bank of New Zealand (RBNZ)',
    historicalData: generateSparklineData(0.605, 12, 0.0005),
  },
];